### PR TITLE
setting ~use_map_topic parameter 

### PR DESCRIPTION
**Pull request by Jailander**
this commit solves #44

### CODE REVIEW

**Comment by nilsbore** [comment]
Sorry for being late on this, I'm working hard to finish my ICRA paper.

**Comment by Jailander** [comment]
no problem, it was just a line on the launch file, we found the problem on Saturday and applied this solution, should be tested elsewhere

**Comment by nilsbore** [comment]
Yeah, for some really weird reason we're unable to launch two map servers at once on Rosie.

**Comment by Jailander** [comment]
but is it happening after you applied this change or before?

**Comment by nilsbore** [comment]
Before, I haven't tried after, maybe this can fix it.

**Comment by marc-hanheide** [comment]
Jaime, you changed the layout of the file a lot... is that needed?

**Comment by Jailander** [comment]
well it had a lot of annoying tabs and spaces I was just making it look nice, is not necessary though

**Comment by marc-hanheide** [comment]
sorry... I abused this pull request for some jenkins testing... explaining the open-close-orgy above

**Pull request merged**
